version: '2.2'
services:
  rally-tests:
    build:
      context: .
      args:
        - NEW_USER_UID=${UID}
        - NEW_USER=${USER}
    container_name: rally-tests
    volumes:
      - $HOME/.gitconfig:/home/${USER}/.gitconfig
      - $HOME/.github:/home/${USER}/.github
      - $HOME/.gnupg:/home/${USER}/.gnupg
      - ${PWD}/.:/home/${USER}/rally
    image: rally-tests
    user: ${UID}
    working_dir: /home/${USER}/rally
    stdin_open: true
    tty: true
