#!/usr/bin/env bash

# fail this script immediately if any command fails with a non-zero exit code
set -e
# Treat unset env variables as an error
set -u
# fail on pipeline errors, e.g. when grepping
set -o pipefail

# We assume here that this script will stay in the Rally git root directory (it does not make sense in any other place anyway)

# see http://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
RALLY_SRC_HOME="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

pushd . >/dev/null 2>&1
cd "${RALLY_SRC_HOME}" >/dev/null 2>&1

# ensure the Actor system can find Rally sources
export PYTHONPATH="${RALLY_SRC_HOME}:${PYTHONPATH}"

# set variables that are needed for run.sh
__RALLY_INTERNAL_BINARY_NAME="esrallyd"
__RALLY_INTERNAL_HUMAN_NAME="Rally daemon"

source run.sh
