version: '2.2'
services:
  metricsstore:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es01
    environment:
      - cluster.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - metricsesdata1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - metricsstorenet
    healthcheck:
      test: curl -s http://localhost:19200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 3s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - metricsstorenet

volumes:
  metricsesdata1:
    driver: local

networks:
  metricsstorenet:
