agents:
  provider: "gcp"
  image: family/core-ubuntu-2204
  machineType: "n1-standard-8"

steps:
  - label: "Run 3.8 integration tests :test_tube:"
    command: bash .buildkite/it/run.sh 3.8
  - label: "Run 3.12 integration tests :test_tube:"
    command: bash .buildkite/it/run.sh 3.12
