agents:
  provider: "gcp"
  machineType: "n4-standard-2"
  diskType: hyperdisk-balanced
  image: family/core-ubuntu-2204

steps:
  - input: "Build parameters"
    # If the build is triggered by merging a PR to master, we want to build from the master branch.
    # If the build is triggered by a schedule, we want to build from the current branch
    if: '!((build.source == "webhook" && build.branch == "master") || build.source == "schedule")'
    fields:
      - text: "BUILD_FROM_BRANCH"
        key: "BUILD_FROM_BRANCH"
        default: ""
        hint: "The branch to build from e.g. 'master'. Leave blank to build from the current branch: $BUILDKITE_BRANCH."
        required: false
      - select: "PUBLIC_DOCKER_REPO"
        key: "PUBLIC_DOCKER_REPO"
        hint: "Push the Docker image to the public Docker registry (default: No)."
        default: "false"
        options:
          - label: "Yes"
            value: "true"
          - label: "No"
            value: "false"
      - select: "PUSH_LATEST"
        key: "PUSH_LATEST"
        hint: "Push the <branch>-latest tag to the registry."
        default: "true"
        options:
          - label: "Yes"
            value: "true"
          - label: "No"
            value: "false"
  - wait
  - label: ":docker: Build Docker Artifacts for Rally amd64"
    command: bash .buildkite/dev-docker/run.sh build amd64
    key: "amd64"
    retry:
      automatic:
        - limit: 1
    timeout_in_minutes: 20
  - label: ":docker: Build Docker Artifacts for Rally arm64"
    command: bash .buildkite/dev-docker/run.sh build arm64
    key: "arm64"
    retry:
      automatic:
        - limit: 1
    timeout_in_minutes: 20
    agents:
      machineType: "n4a-standard-2"
      image: family/core-ubuntu-2204-aarch64
      # reduced list of zones
      zones: us-east1-b,us-east1-c,us-central1-a,us-central1-b,us-central1-c,us-west1-c
  - label: ":docker: build docker manifest"
    command: bash .buildkite/dev-docker/run.sh manifest
    key: "manifest"
    timeout_in_minutes: 5
    depends_on:
      - "amd64"
      - "arm64"
