agents:
  provider: "gcp"
  zone: "us-central1-a"

steps:
  - input: "Build parameters"
    fields:
      - text: "BUILD_FROM_BRANCH"
        key: "BUILD_FROM_BRANCH"
        default: "master"
        hint: "The branch to build from e.g. 'master'."
  - wait
  - label: ":docker: Build Docker Artifacts for Rally amd64"
    command: bash .buildkite/dev-docker/run.sh amd64
    # Run on GCP to use `docker`
    agents:
      machineType: "n2-standard-8"
      image: family/core-ubuntu-2204
  - label: ":docker: Build Docker Artifacts for Rally arm64"
    command: bash .buildkite/dev-docker/run.sh arm64
    # Run on GCP to use `docker`
    agents:
      machineType: "t2a-standard-8"
      image: family/core-ubuntu-2204-aarch64
