steps:
  - input: "Build parameters"
    fields:
      - text: "BUILD_FROM_BRANCH"
        key: "BUILD_FROM_BRANCH"
        default: "master"
        hint: "The branch to build from e.g. 'master'."
  - wait
  - label: "Build Docker Artifacts for Rally"
    command: bash .buildkite/dev-docker/run.sh
    # Run on GCP to use `docker`
    agents:
      provider: gcp
