agents:
  provider: "gcp"
  machineType: "n4-standard-4"
  diskType: hyperdisk-balanced
  image: family/core-ubuntu-2204

steps:
  - input: "Build parameters"
    fields:
      - text: "RELEASE_VERSION"
        key: "RELEASE_VERSION"
        default: ""
        hint: "The version to release e.g. '2.8.0'."
      - select: "PUSH_LATEST"
        key: "PUSH_LATEST"
        hint: "Update the latest tag in the registry."
        # True, because we want the scheduled pipeline to update the latest tag, eventually
        default: "true"
        options:
          - label: "Yes"
            value: "true"
          - label: "No"
            value: "false"

  - wait
  - label: "Release Docker Artifacts for Rally"
    command: bash .buildkite/release-docker/run.sh build amd64
    # Run on GCP to use `docker`
    key: "amd64"
    retry:
      automatic:
        - limit: 1
    timeout_in_minutes: 20
  - label: "Release Docker Artifacts for Rally"
    command: bash .buildkite/release-docker/run.sh build arm64
    # Run on GCP to use `docker`
    key: "arm64"
    retry:
      automatic:
        - limit: 1
    timeout_in_minutes: 20
    agents:
      machineType: "n4a-standard-4"
      image: family/core-ubuntu-2204-aarch64
      # reduced list of zones
      zones: us-east1-b,us-east1-c,us-central1-a,us-central1-b,us-central1-c,us-west1-c
  - label: ":docker: build docker manifest"
    command: bash .buildkite/release-docker/run.sh manifest
    timeout_in_minutes: 5
    key: "manifest"
    depends_on:
      - "amd64"
      - "arm64"
