name: OpenSearch Benchmark Actions
on: [pull_request]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clone pyenv
        run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
      - name: Run the CI build script
        run: bash .ci/build.sh build
        env:
          RALLY_HOME: env.GITHUB_WORKSPACE
