name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run the CI build script
        run: | 
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          bash .ci/build.sh build
        env:
          RALLY_HOME: env.GITHUB_WORKSPACE
      - run: echo "🍏 This job's status is ${{ job.status }}."
